### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'getIntersectionPtsWithLinearObject'


### ISSUE THREAD

**Issue by peter-shr** [gam17/QAD#15]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_offset_maptool.py", line 136, in canvasMoveEvent
    self.addOffSetGeometries(self.tmpPoint)
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_offset_maptool.py", line 117, in addOffSetGeometries
    tolerance2ApproxCurve)
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_utils.py", line 6094, in offSetPolyline
    untrimmedOffsetPartList = getUntrimmedOffSetPartList(partList, offSetDist, offSetSide, gapType, tolerance)
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_utils.py", line 5567, in getUntrimmedOffSetPartList
    return virtualPartClipping(untrimmedOffsetPartList, virtualPartPositionList)
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_utils.py", line 5680, in virtualPartClipping
    ptIntList = prevPart.getIntersectionPtsWithLinearObject(nextPart)
AttributeError: 'NoneType' object has no attribute 'getIntersectionPtsWithLinearObject'

```
qad 2.14.1, QGIS 2.18.7 on Windows 8

**Comment by gam17** [comment]
Hi Peter,
   to reproduce the error I need a shape file with the geometry you are running offset command to. I need the offset value too.
Thank you
bye

**Comment by gam17** [comment]
Fixed. Wait for the next realese...
