### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'getEndPt'


### ISSUE THREAD

**Issue by peter-shr** [gam17/QAD#24]
Steps to reproduce
 1. First - PEDIT
 2. Second - Select Lineobjekt for edit
 3. Third  - Error

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_maptool.py", line 197, in <lambda>
    shot = lambda: self.displayPopupMenuOnGrip(pos, entityGripPoint.entity, gripPoint)
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad_maptool.py", line 469, in displayPopupMenuOnGrip
    if gripPoint.isIntersecting(linearObject.getEndPt()):
AttributeError: 'NoneType' object has no attribute 'getEndPt'

```
qad 2.14.2, QGIS 2.14.22-Essen on Windows 10

**Comment by gam17** [comment]
Hi peter-shr,
   I cannot reproduce the error. Can you send me some data (a shape
file) and a small video to help me to reproduce the error, please ?
Thank you 
gam17

**Comment by gam17** [comment]
Closed due to lack of feedback
