### ISSUE TITLE
Not able to load QAD plugin (future issue?)

### ISSUE THREAD

**Issue by rduivenvoorde** [gam17/QAD#43]
Thought to load QAD plugin in QGIS3, but got this error:

![Screenshot-20200421165845-1250x606](https://user-images.githubusercontent.com/731673/79881510-93e77d00-83f1-11ea-84ab-f63c28dc6fcd.png)

I get the feeling that it is something to do with 'clock' not being available anymore in python3's 'time' module?
I do have `python3-future` installed:
`python3-future is already the newest version (0.18.2-2).`

Googling I found: https://github.com/wonderworks-software/PyFlow/issues/79
` it seems the solution is simply replacing time.clock() with time.process_time()`

BUT I did not find a `from time import clock` apparently that comes from future...
So I just commented out `from future.backports.test.pystone import TRUE` in

```
  qad/qad_dynamicinput.py", line 47, in 
    from future.backports.test.pystone import TRUE
```
And then the plugin at least loads with me.
Not sure what this breaks though :-)

In text the error is:

```
Couldn't load plugin 'qad' due to an error when calling its classFactory() method 

ImportError: cannot import name 'clock' from 'time' (unknown location) 
Traceback (most recent call last):
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/__init__.py", line 28, in classFactory
    from .qad import Qad
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad.py", line 41, in 
    from .qad_maptool import QadMapTool
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_maptool.py", line 38, in 
    from .qad_getpoint import QadGetPointDrawModeEnum
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_getpoint.py", line 46, in 
    from .qad_dynamicinput import QadDynamicEditInput, QadDynamicInputContextEnum
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_dynamicinput.py", line 47, in 
    from future.backports.test.pystone import TRUE
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/future/backports/test/pystone.py", line 37, in 
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Comment by gam17** [comment]
Hi Richard,
   that code row is not useful, I erased it.
Thank you for making qad a better plugin
gam17
