### ISSUE TITLE
QAD Plugin crashes QGIS when loading

### ISSUE THREAD

**Issue by ArArgyridis** [gam17/QAD#62]
Hello, 
I am using QGIS 3.22 with latest QAD from QGIS Repositories and get the following error:

TypeError: arguments did not match any overloaded call:   resize(self, QSize): argument 1 has unexpected type 'int'   resize(self, int, int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'int'
  resize(self, int, int): argument 2 has unexpected type 'float'

Python version: 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0] 
QGIS version: 3.22.2-Białowieża Białowieża, exported 

Python Path:
/usr/share/qgis/python
/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python
/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python3.10/site-packages
/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python
/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DeepLearningTools

**Comment by gam17** [comment]
Hi, can you download the last QAD release from github. Try it and tell me if it is fixed.

**Comment by ArArgyridis** [comment]
Hello,

I just tried it, this error is gone, but now another one exists when I try to use e.g. the move, or scale tools:

Well, this is embarrassing !

Inappropriate argument type.
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/qad_dynamicinput.py", line 2878, in moveCtrls
    self.edits[QadDynamicInputEditEnum.EDIT_DIST_PREV_PT].move(editPt.x(), editPt.y())
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/qad_dynamicinput.py", line 2775, in mouseMoveEvent
    self.moveCtrls(mousePos)
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/qad_dynamicinput.py", line 2535, in show
    self.mouseMoveEvent(mousePos)
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/qad_getpoint.py", line 677, in setStartPoint
    self.dynamicEditInput.show(True, self.canvas.mouseLastXY()) # visualizzo e resetto input dinamico
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/cmd/qad_move_maptool.py", line 141, in setMode
    self.setStartPoint(self.basePt)
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/cmd/qad_move_cmd.py", line 223, in run
    self.getPointMapTool().setMode(Qad_move_maptool_ModeEnum.BASE_PT_KNOWN_ASK_FOR_MOVE_PT)
  File "/home/argyros/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD/qad_commands.py", line 337, in continueCommandFromMapTool
    if self.actualCommand.run(True) == True: # comando terminato

**Comment by gam17** [comment]
Sorry for the errors, something must be changed in the last QGIS release.
Can you try with the last QAD release from github? Tell me if it is fixed, please.

**Comment by ArArgyridis** [comment]
Hello again,

I tried with latest QGIS (3.22) and it seems that the problem has been resolved. Thanks a lot!

**Comment by kikislater** [comment]
Same issue with QGIS 3.22 or 3.24. 
Issue is related to python 3.10 

```
TypeError: arguments did not match any overloaded call:   resize(self, QSize): argument 1 has unexpected type 'int'   resize(self, int, int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/sylvain/.local/share/QGIS/QGIS3/profiles/sylvain/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "/home/sylvain/.local/share/QGIS/QGIS3/profiles/sylvain/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'int'
  resize(self, int, int): argument 2 has unexpected type 'float'


Version de Python : 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] 
Version de QGIS : 3.24.0-Tisler Tisler, exported 
```

Code needs update

**Comment by rduivenvoorde** [comment]
Yep, this is a Python 3.10 issue...  just wanted to create the same issue (I'm on Debian testing and having this error, not only in this plugin, but in more...)

**Comment by kikislater** [comment]
> Yep, this is a Python 3.10 issue... just wanted to create the same issue (I'm on Debian testing and having this error, not only in this plugin, but in more...)

Do you have a list of these plugins ?

**Comment by gam17** [comment]
closed
