### ISSUE TITLE
QAD don't set up

### ISSUE THREAD

**Issue by axinav** [gam17/QAD#63]
I load plugin from Qgis repository.
AttributeError: 'QVariant' object has no attribute 'split' 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/__init__.py", line 29, in classFactory
    return Qad(iface)
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad.py", line 409, in __init__
    userLocaleList = QSettings().value("locale/userLocale").split("_")
AttributeError: 'QVariant' object has no attribute 'split'
My OS is Manjaro: Operating System: Manjaro Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Qgis version 3.22.3

**Comment by gam17** [comment]
Hi axinav,
   sorry for the inconvenience, this is due to the Qt version 5 which
work differently from the previous ones.
Actually use a previous QGIS version.
In the future I will port QAD to QT5...
gam17

**Comment by axinav** [comment]
Thank you so much for your plugin. I was constantly using QAD in QGIS 2.
I fixed this bug myself. I substituted the list [ru,RU] instead of calling QSettings.value().
