### ISSUE TITLE
Error when trying to trim a line to a circle

### ISSUE THREAD

**Issue by Jopie01** [gam17/QAD#68]
I have some circles and lines crossing them. Now I want to trim the part of the line which is in the circle. So I select the 'trim' command, select the circle and press <ENTER>. Now I select the portion of the line to be removed and QAD shows up an error dialog with
```
Well, this is embarrassing !

Inappropriate argument type.
TypeError: QgsGeometry.fromRect(): argument 1 has unexpected type 'NoneType'
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_multi_geom.py", line 1276, in insertBoundingBox
    newFeature.setGeometry(QgsGeometry().fromRect(boundingBox))
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_multi_geom.py", line 1249, in __init__
    error = True if self.insertBoundingBox(geom.getBoundingBox(), geomAt, subGeomAt, partAt) == False else False
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_geom_relations.py", line 896, in twoGeomObjects
    object2GeomBoundingBoxCache = QadGeomBoundingBoxCache(object2)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_extend_trim_fun.py", line 277, in getIntersectionPtsTrimQadGeometry
    return QadIntersections.twoGeomObjects(qadGeom, limitGeom)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_extend_trim_fun.py", line 192, in trimQadGeometry
    intPts.extend(getIntersectionPtsTrimQadGeometry(subGeom, limitEntity.getQadGeom(), edgeMode))
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/cmd/qad_trim_cmd.py", line 155, in trimFeatures
    result = trimQadGeometry(qadGeom, intPt, \
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/cmd/qad_trim_cmd.py", line 359, in run
    self.trimFeatures(QadPoint().set(value), ToExtend)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_commands.py", line 337, in continueCommandFromMapTool
    if self.actualCommand.run(True) == True: # comando terminato
```
What am I doing wrong? I also got the following traceback:
```
An error has occurred while executing Python code: 

TypeError: QgsGeometry.fromRect(): argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_getpoint.py", line 763, in canvasMoveEvent
    return self.canvasMoveEventOnPointSel(event)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_getpoint.py", line 841, in canvasMoveEventOnPointSel
    oSnapPoints = self.__QadSnapper.getSnapPoint(self.tmpEntity, point, \
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_snapper.py", line 502, in getSnapPoint
    staticSnapPoints = self.getStaticSnapPoints(g, gPart, isTemporaryGeom)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_snapper.py", line 587, in getStaticSnapPoints
    result[QadSnapTypeEnum.INT] = self.getIntPoints(gPart, isTemporaryGeom)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_snapper.py", line 834, in getIntPoints
    geomBoundingBoxCache = QadGeomBoundingBoxCache(geom)
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_multi_geom.py", line 1249, in __init__
    error = True if self.insertBoundingBox(geom.getBoundingBox(), geomAt, subGeomAt, partAt) == False else False
  File "/usr/share/local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_multi_geom.py", line 1276, in insertBoundingBox
    newFeature.setGeometry(QgsGeometry().fromRect(boundingBox))
TypeError: QgsGeometry.fromRect(): argument 1 has unexpected type 'NoneType'

Python version: 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] 
QGIS version: 3.20.3-Odense Odense, exported 
```
So it seems there is something wrong with circles?

**Comment by Jopie01** [comment]
Did some debugging and testing. I think I found the problem, see https://github.com/gam17/QAD/blob/c223abd4cf39c7099116ccdf6d746f40d5e16af7/qad_circle.py#L116-L120 
The `boundingbox` function doesn't return anything so it will become `None` and this gives the error of `NoneType`. So I changed the function into
```python
#===============================================================================
# getBoundingBox
#===============================================================================
def getBoundingBox(self):
   """
   la funzione ritorna il rettangolo che racchiude il cerchio.
   """
   cx = self.center.x()
   cy = self.center.y()

   xBottomLeft = cx - self.radius
   xTopRight = cx + self.radius
   yBottomLeft = cy - self.radius
   yTopRight = cy + self.radius

   return QgsRectangle(xBottomLeft, yBottomLeft, xTopRight, yTopRight)
```
And now I can trim lines and circles.

**Comment by gam17** [comment]
thank you very much to make qad a better plugin
