### ISSUE TITLE
causes fatal error in QGIS 3.30.3

### ISSUE THREAD

**Issue by jack-sprat** [gam17/QAD#75]
Installing plug-in causes infinite pop-up

Error:
TypeError: arguments did not match any overloaded call:   resize(self, a0: QSize): argument 1 has unexpected type 'int'   resize(self, w: int, h: int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'

Python version: 3.11.3 (main, Apr 27 2023, 22:08:21) [GCC] 
QGIS version: 3.30.3-'s-Hertogenbosch 's-Hertogenbosch, exported 

Python Path:
/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio
/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks
/usr/share/qgis/python
/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python
/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib64/python311.zip
/usr/lib64/python3.11
/usr/lib64/python3.11/lib-dynload
/usr/lib64/python3.11/site-packages
/usr/lib64/python3.11/site-packages/PIL
/usr/lib64/python3.11/_import_failed
/usr/lib/python3.11/site-packages
/home/jeremy/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by aseido222** [comment]
Hi, I'm on Debian 12 and I have de same error and crash...
TypeError: arguments did not match any overloaded call:   resize(self, a0: QSize): argument 1 has unexpected type 'int'   resize(self, w: int, h: int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/seisdedo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "/home/seisdedo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'


Versión de Python: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] 
Versión de QGIS: 3.32.0-Lima Lima, 311a8cb8a6 

Ruta de Python:
/usr/share/qgis/python
/home/seisdedo/.local/share/QGIS/QGIS3/profiles/default/python
/home/seisdedo/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python311.zip
/usr/lib/python3.11
/usr/lib/python3.11/lib-dynload
/usr/local/lib/python3.11/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.11/dist-packages
/home/seisdedo/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by gam17** [comment]
Hi jack-sprat and aseido222,
   can you try the QAD version in this github repository ?
Let me know if the problem persists...
thank you
gam17

**Comment by DeanCording** [comment]
I've tried the current version in this github repository but it now fails with a different error:

```
Couldn't load plugin 'QAD-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'networkx' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/__init__.py", line 28, in classFactory
    from .qad import Qad
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad.py", line 43, in 
    from .qad_maptool import QadMapTool
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_maptool.py", line 38, in 
    from .qad_getpoint import QadGetPointDrawModeEnum
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_getpoint.py", line 38, in 
    from .qad_snapper import QadSnapper, QadSnapModeEnum, QadSnapTypeEnum, snapTypeEnum2Str
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_snapper.py", line 33, in 
    from .qad_geom_relations import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dean/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QAD-master/qad_geom_relations.py", line 35, in 
    from networkx.generators import line
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'networkx'


Python version: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] 
QGIS version: 3.34.3-Prizren Prizren, 47373234acd 
```

**Comment by gam17** [comment]
Hi Dean,
   in the  3.34.3 QGIS version there isn't the module named 'networkx', probably.
Can you retry the current version in this github repository ?
