### ISSUE TITLE
QAD Error in the new QGIS version 3.34 Prizren installed in Ubuntu  22.04.4 LTS

### ISSUE THREAD

**Issue by uxuech** [gam17/QAD#79]
Hello, I have updated the new version of QGIS and it gives me the following error related to the QAD Plugin.

```

TypeError: arguments did not match any overloaded call:   resize(self, QSize): argument 1 has unexpected type 'int'   resize(self, int, int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'int'
  resize(self, int, int): argument 2 has unexpected type 'float'


Versión de Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versión de QGIS: 3.34.4-Prizren Prizren, exported 

Ruta de Python:
/usr/share/qgis/python
/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python
/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/uxuech/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.10/dist-packages
/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python
/home/uxuech/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/requests_oauthlib-1.3.1-py2.py3-none-any.whl
```
Do you know how can I solve it?
Thanks in advance

**Comment by gam17** [comment]
HI uxuech,
   try the updated qad version in github. It should work. Let me know...

**Comment by gam17** [comment]
I assume it works now
