### ISSUE TITLE
QAD Error in the new version 3.36 Maidenhead (also 3.34)

### ISSUE THREAD

**Issue by GIS-ela** [gam17/QAD#81]
### Hi, I´m getting this failure when opening QGIS:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

TypeError: arguments did not match any overloaded call:   resize(self, a0: QSize): argument 1 has unexpected type 'int'   resize(self, w: int, h: int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'

**Python-Version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.36.2-Maidenhead Maidenhead, 6d250527** 

Python-Pfad:
C:/OSGeo4W/apps/qgis/./python
C:/Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\AWAGNER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

### Trying to use QAD, this error occurs clicking once in the map:

Well, this is embarrassing !

Inappropriate argument type.
TypeError: arguments did not match any overloaded call:
move(self, a0: QPoint): argument 1 has unexpected type 'float'
move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dynamicinput.py", line 2878, in moveCtrls
self.edits[QadDynamicInputEditEnum.EDIT_DIST_PREV_PT].move(editPt.x(), editPt.y())
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dynamicinput.py", line 2775, in mouseMoveEvent
self.moveCtrls(mousePos)
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dynamicinput.py", line 2535, in show
self.mouseMoveEvent(mousePos)
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_getpoint.py", line 677, in setStartPoint
self.dynamicEditInput.show(True, self.canvas.mouseLastXY()) # visualizzo e resetto input dinamico
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\cmd\qad_line_maptool.py", line 137, in setMode
self.setStartPoint(self.firstPt)
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\cmd\qad_line_cmd.py", line 357, in run
self.getPointMapTool().setMode(Qad_line_maptool_ModeEnum.FIRST_PT_KNOWN_ASK_FOR_SECOND_PT)
File "C:\Users/AWAGNER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_commands.py", line 337, in continueCommandFromMapTool
if self.actualCommand.run(True) == True: # comando terminato
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### I´ve installed QAD in QGIS because I don´t know how to do it via GitHub. Hope someone can help. Thx!

**Comment by gam17** [comment]
HI GIS-ela,
try the updated qad version in github. It should work. Let me know...
From the page https://github.com/gam17/QAD press the button "Code" and then select "Download zip".
The zip contains a folder called "QAD-master". Copy the files contained in that folder into the qad installation folder.
For windows it should be "C:\Users\ <your user> \AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qad

**Comment by em-rezende** [comment]
**Dear,
I downloaded the new version of QAD from https://github.com/gam17/QAD (2024-05-04)
When I open sample_data/dimension.qgs it shows this error.
------------------------------------------------------------------**

Um erro ocorreu enquanto executava o código Python: 

AttributeError: 'QadRawConfigParser' object has no attribute 'readfp'. Did you mean: 'read'? 
Traceback (most recent call last):
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad.py", line 689, in onProjectLoaded
    self.initOnProjectLoaded()
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad.py", line 509, in initOnProjectLoaded
    self.loadDimStyles()
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad.py", line 364, in loadDimStyles
    QadDimStyles.load()
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dim.py", line 4568, in load
    self.load(_dir, True) # in append
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dim.py", line 4588, in load
    if dimStyle.load(path) == True:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dim.py", line 752, in load
    config.readfp(codecs.open(_path, "r", "utf-8"))
    ^^^^^^^^^^^^^
AttributeError: 'QadRawConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?


Versão do Python: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Versão do QGIS: 3.36.2-Maidenhead Maidenhead, 6d250527 

Caminho do Python:
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass83\etc\python
C:\Users\Ezequiel\Documents
C:\Program Files\QGIS 3.36.2\bin\python312.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib
C:\Program Files\QGIS 3.36.2\bin
C:\PROGRA~1\QGIS33~1.2\apps\Python312
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/qad/sample_data

**------------------------------------------------------------------
The "STANDARD" sizing style does not appear either.
When I create a new sizing style in the "DB" tab, in "Text" it shows another error:
------------------------------------------------------------------**

Um erro ocorreu enquanto executava o código Python: 

TypeError: setPixelSize(self, a0: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dimstyle_details_dlg.py", line 209, in idFieldNameChanged
    self.redrawDimOnDBTabChanged()
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dimstyle_details_dlg.py", line 194, in redrawDimOnDBTabChanged
    self.previewDim.drawDim(self.dimStyle)
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dimstyle_details_dlg.py", line 1056, in drawDim
    dimEntity, textOffsetRectGeom = self.dimStyle.getLinearDimFeatures(self.plugIn.canvas, \
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_dim.py", line 3682, in getLinearDimFeatures
    textWidth, textHeight = qad_label.calculateLabelSize(self.getTextualLayer(), textFeature, canvas)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_label.py", line 497, in calculateLabelSize
    font.setPixelSize(fontSize * 100)
TypeError: setPixelSize(self, a0: int): argument 1 has unexpected type 'float'


Versão do Python: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Versão do QGIS: 3.36.2-Maidenhead Maidenhead, 6d250527 

Caminho do Python:
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass83\etc\python
C:\Users\Ezequiel\Documents
C:\Program Files\QGIS 3.36.2\bin\python312.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib
C:\Program Files\QGIS 3.36.2\bin
C:\PROGRA~1\QGIS33~1.2\apps\Python312
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Ezequiel/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/qad/sample_data

**Comment by GIS-ela** [comment]
Hi, sorry for the late response. The former update worked, hence with some crashes now and then on my PC. Thanks for that! :) But the latest update from github results in the failure below. QAD doesn´t work. Unfortunately I´ve overwritten the former code, so there´s no chance for me in the moment to use QAD and I kind of have to for my work as a transport engineer. :(

**Comment by gam17** [comment]
Hi, it seems your QGIS has not scipy library already installed.
It is strange because I have installed last LTR QGIS version and I found
it.
Anyway try to install scipy library with the following code from the
QGIS Python console:

import pip
pip.main(['install', 'scipy'])

let me know...

gam17
